Support for ETP-385
the-events-calendar/tribe-common pull request #1426
Opened 2020-08-15 23:48 UTC by cliffordp

🎫 [ETP-385] - to support https://github.com/moderntribe/event-tickets-plus/pull/1025

2020-09-03 04:31 UTC, sc0ttkclark commented on src/Tribe/Shortcode/Shortcode_Abstract.php
> +	protected $aliased_arguments = [
Can we get a screencast / example of this working as intended?

2020-09-03 04:31 UTC, sc0ttkclark commented on src/Tribe/Shortcode/Shortcode_Abstract.php
> +	protected $aliased_arguments = [
Also we should check other shortcodes to make sure they don't conflict

2020-09-03 04:31 UTC, sc0ttkclark requested changes
Needs artifact and confirmation there are no conflicting arguments

2021-11-29 15:13 UTC, borkweb commented
This is stale and archived elsewhere. Closing this PR and deleting the branch.

2021-11-29 15:13 UTC, closed without merging