Fix issue with Select2 in The Events Calendar.
the-events-calendar/tribe-common pull request #1458
Opened 2020-10-15 17:37 UTC by mmcachran

This fixes an issue in The Events Calendar when the Select2 container cannot be found.

**Original Error Message:**
<img width="1345" alt="Screen Shot 2020-10-15 at 1 36 59 PM" src="https://user-images.githubusercontent.com/375068/96166156-967fe680-0eeb-11eb-95d9-f6303bc934dd.png">

2020-10-15 17:41 UTC, sc0ttkclark reviewed
Looks good to me, though I'm not entirely sure why TEC would call this and not have the element there. Might be good for follow up before this moves forward.

2020-10-16 09:04 UTC, lucatume commented
I've changed the assignee from myself to @bordoni as this is more of his area of operations.

2020-10-16 09:06 UTC, lucatume requested changes

2020-10-16 09:06 UTC, lucatume commented on src/resources/js/dropdowns.js
> +			// Propagating original input classes to the select2 container.
This comment should, probably, be removed or modified.
```suggestion

```

2020-10-16 15:40 UTC, paulmskim commented
This is an issue of having 2 different versions of select2 loading. We run select2 4.X, but when select2 3.X is loaded as well, it creates this problem. We may need to look into how to prevent having more than 1 version of select2 loading at the same time or deal with potential conflicts gracefully.

It's known that ACF loads select2 3.X in earlier versions, and updating to a later version of ACF fixes this. This could very well also be the case with other plugins.

2021-04-15 04:08 UTC, bordoni commented
This problem will be resolved by #1573

2021-04-15 04:08 UTC, closed without merging