Feature/customizer phase 4 b
the-events-calendar/tribe-common pull request #1616
Opened 2021-07-06 19:02 UTC by Camwyn

2021-07-08 01:08 UTC, paulmskim commented
looks like you have a number of lint issues. also, should this be based off of danish?

2021-07-19 02:00 UTC, bordoni requested changes

2021-07-19 02:00 UTC, bordoni commented on src/Tribe/Utils/Color.php
> +	public function getHexWithHash() {
New method should use correct code standards.

2021-07-19 08:09 UTC, paulmskim commented on src/Tribe/Customizer/Controls/Toggle.php
> +					} ?>
@bordoni has an extra bracket in his suggestion, but otherwise agreed.

2021-07-29 09:48 UTC, paulmskim requested changes

2021-07-29 09:48 UTC, paulmskim commented on src/Tribe/Customizer.php
> +	 * Undocumented function
docblock description

2021-07-29 09:48 UTC, paulmskim commented on src/Tribe/Customizer/Controls/Number.php
> +?>
no closing tag

2021-07-29 09:48 UTC, paulmskim commented on src/Tribe/Customizer/Controls/Number.php
> +		$name             = '_customize-radio-' . $this->id;
name should be number, not radio

2021-07-29 09:48 UTC, paulmskim commented on src/Tribe/Customizer/Controls/Number.php
> +			<span id="<?php echo esc_attr( $description_id ); ?>" class="description customize-control-description"><?php echo $this->description; ?></span>
should the description be escaped? same question for the other controls

2021-07-29 09:48 UTC, paulmskim commented on src/Tribe/Customizer/Controls/Range_Slider.php
> +						><?php echo esc_html( $label ); ?></div>
```suggestion
						<div
							class="tec-range-slider-option"
							value="<?php echo esc_attr( $value ); ?>"
							label="<?php echo esc_attr( $label ); ?>"
						>
							<?php echo esc_html( $label ); ?>
						</div>
```

2021-07-29 09:48 UTC, paulmskim commented on src/Tribe/Customizer/Controls/Range_Slider.php
> +					<?php foreach( $this->choices as $label => $value) : ?>
```suggestion
					<?php foreach ( $this->choices as $label => $value ) : ?>
```

2021-07-29 09:48 UTC, paulmskim commented on src/Tribe/Customizer/Controls/Range_Slider.php
> +					</div>
```suggestion
				</div>
```

2021-07-29 09:48 UTC, paulmskim commented on src/Tribe/Customizer/Controls/Toggle.php
> +				<?php } ?>
```suggestion
				<?php if ( ! empty( $this->choices['on'] ) ) : ?>
					<span class="toggle-label-on">
						<?php echo wp_kses_post( $this->choices['on'] ); ?>
					</span>
				<?php endif; ?>
```

2021-07-29 09:48 UTC, paulmskim commented on src/Tribe/Customizer/Section.php
> +		: tribe( 'customizer' )->get_option( [ $section, $option ] );
```suggestion
		$color = is_null( $section )
			? tribe( 'customizer' )->get_option( [ $this->ID, $option ] )
			: tribe( 'customizer' )->get_option( [ $section, $option ] );
```

2021-07-29 09:48 UTC, paulmskim commented on src/Tribe/Utils/Color.php
>  	/**
let's add new lines between these functions

2021-07-29 09:48 UTC, paulmskim commented on src/resources/postcss/common-full.pcss
> +@import "utilities/_variables-skeleton.pcss";
shouldn't need this, since common skeleton should load the variables for us.

2021-07-29 09:48 UTC, paulmskim commented on src/resources/postcss/customizer-controls.pcss
> +@import "utilities/_all.pcss";
do we need the variables skeleton here too? i'm seeing some spacers in this file.

2021-07-29 09:48 UTC, paulmskim commented on src/resources/postcss/customizer-controls.pcss
> +		}
don't need this, you've added the visually hide class on the label

2021-07-29 09:48 UTC, paulmskim commented on src/resources/postcss/customizer-controls.pcss
> +			-webkit-appearance: none;
just use `appearance`, the build process will take care of the prefixing

2021-07-29 09:48 UTC, paulmskim commented on src/resources/postcss/customizer-controls.pcss
> +				-webkit-appearance: none;
just use `appearance`, the build process will take care of prefixing.

2021-07-29 09:48 UTC, paulmskim commented on src/resources/postcss/customizer-controls.pcss
> +				@mixin visually-hide;
maybe add the visually hide class instead?

2021-08-02 16:59 UTC, Camwyn commented on src/Tribe/Customizer/Controls/Range_Slider.php
> +						><?php echo esc_html( $label ); ?></option>
Converted this from a datalist to nested divs for browser compatibility

2021-08-05 14:07 UTC, bordoni approved these changes

2021-08-05 15:46 UTC, merged