[CE-97] Fix ampersands displaying encoded
the-events-calendar/tribe-common pull request #1620
Opened 2021-07-13 18:49 UTC by redscar

[CE-97]

Ampersands were displaying encoded. This change displays them properly for all drop-downs that gather the data via Ajax. The change was made because of a bug reported in CE. If you had any categories or tags with an ampersand they would display escaped.

![image](https://user-images.githubusercontent.com/12241059/125508185-74a90624-dd3f-49a5-828d-241a4eb37cde.png)

![image](https://user-images.githubusercontent.com/12241059/125508213-431c2a24-a188-47fd-9c7d-b8b0eba34c24.png)

2021-07-15 18:44 UTC, borkweb requested changes
One tiny change!

2021-07-15 18:44 UTC, borkweb commented on src/Tribe/Ajax/Dropdown.php
> +			$result->text = htmlspecialchars_decode( $result->text );
Let's make sure we escape scary stuff:

```suggestion
			$result->text = wp_kses_post( htmlspecialchars_decode( $result->text ) );
```

2021-07-19 05:40 UTC, bordoni submitted a review, later dismissed

2021-07-23 16:45 UTC, bordoni approved these changes

2021-07-23 16:45 UTC, merged