Don't tell wp_query it's a search if the search term(s) are empty.
the-events-calendar/tribe-common pull request #1623
Opened 2021-07-28 17:55 UTC by Camwyn

The issue:
Wild snippets out there try to exclude pages from post searches and in the process remove all post types _except_ `post`.

This breaks our views - as the repository adds a blank search to every event query ( `'s' = ''` ) triggering `$wp_query->is_search` to be true.

This just tests for a search term before adding the search param to the query.

[TEC-4012]

2021-08-03 15:29 UTC, lucatume requested changes

2021-08-03 15:29 UTC, lucatume commented on src/Tribe/Repository.php
> +				if ( ! empty( $value ) ) {
I would make the comparison stricter. String zero, (`"0"`) will evaluate to empty while still being a legit, albeit strange, search term.
```suggestion
				if ( '' !== $value ) ) { 
```

2021-08-04 01:36 UTC, bordoni approved these changes

2021-08-04 01:40 UTC, bordoni approved these changes

2021-08-04 14:22 UTC, merged