Begin moving all editor compatibility into its own file(s).
the-events-calendar/tribe-common pull request #1661
Opened 2021-09-27 17:29 UTC by Camwyn

This PR implements a namespace for the Editor and creates a Compatibility section in it.

Functions that are solely for the "Classic Editor" plugin are moved to that section, out of the main Editor functionality.
All third-party compatibility functionality is now implemented via hooks.

Deprecates unused functions and those moved.

2021-11-05 10:33 UTC, bordoni requested changes

2021-11-05 10:33 UTC, bordoni commented on src/Tribe/Editor.php
> +	public $blocks_editor_key = 'toggle_blocks_editor';
use `static`

2021-11-05 15:12 UTC, bordoni commented on src/Tribe/Editor/Compatibility/Classic_Editor.php
> +		if ( ! self::is_classic_plugin_active() ) {
hahaha

2021-12-03 20:37 UTC, Camwyn commented on src/Tribe/Editor.php
> +		return function_exists( 'gutenberg_register_scripts_and_styles' );
🤦🏼

2021-12-06 18:51 UTC, borkweb requested changes

2021-12-06 18:51 UTC, borkweb commented on src/Tribe/Editor.php
> +	private function is_gutenberg_active() {
We can't change the visibility of this function without risking breakages for folks.
```suggestion
	public function is_gutenberg_active() {
```

2021-12-16 03:21 UTC, closed without merging