In app "end of year sale" promos
the-events-calendar/tribe-common pull request #1684
Opened 2021-12-06 21:14 UTC by skyshab

Last minute in-app "End of year sale" promotions.

2021-12-07 15:57 UTC, borkweb commented
Can we see screenshots of the two notices in place?

2021-12-07 18:00 UTC, bordoni requested changes

2021-12-07 18:00 UTC, bordoni commented on src/Tribe/Admin/Notice/Marketing/End_Of_Year_Sale.php
> +		\Tribe__Assets::instance()->enqueue( [ 'tribe-common-admin' ] );
```suggestion
		tribe_asset_enqueue( [ 'tribe-common-admin' ] );
```

2021-12-07 18:00 UTC, bordoni commented on src/Tribe/Admin/Conditional_Content/End_Of_Year_Sale.php
> + * @since 4.14.7
Lets make sure all sinces are TBD

2021-12-07 18:14 UTC, skyshab commented on src/Tribe/Admin/Notice/Marketing/End_Of_Year_Sale.php
> +		\Tribe__Assets::instance()->enqueue( [ 'tribe-common-admin' ] );
done

2021-12-07 18:14 UTC, skyshab commented on src/Tribe/Admin/Conditional_Content/End_Of_Year_Sale.php
> + * @since 4.14.7
fixed

2021-12-07 18:22 UTC, bordoni approved these changes

2021-12-08 19:42 UTC, codingmusician approved these changes

2021-12-08 20:36 UTC, merged