Fix the crossed wires with the Divi classic editor setting.
the-events-calendar/tribe-common pull request #1696
Opened 2022-01-25 16:53 UTC by Camwyn

[TEC-4088]  

Requires https://github.com/the-events-calendar/tribe-common/pull/1695

2022-02-01 17:44 UTC, bordoni requested changes

2022-02-01 17:44 UTC, bordoni commented on src/Tribe/Main.php
> +		$bar = '';
debug remove.

2022-02-01 17:44 UTC, bordoni commented on src/Tribe/Editor/Compatibility/Divi.php
> +		return 'Divi' == $theme->name || 'Divi' == $theme->template || 'Divi' == $theme->parent_theme;
We shoudl cache this check.

2022-02-01 17:44 UTC, bordoni commented on src/Tribe/Editor/Compatibility/Divi.php
> +	public static $classic_off = 'off';
Docblocks.

2022-02-01 17:44 UTC, bordoni commented on src/Tribe/Editor/Compatibility/Divi.php
> +		}
Invert the check and return.

2022-02-01 17:44 UTC, bordoni commented on src/Tribe/Settings_Manager.php
> +		return self::set_options( $options );
Static?

2022-02-01 18:33 UTC, Camwyn commented on src/Tribe/Settings_Manager.php
> +		return self::set_options( $options );
I followed `set_option()` above?

2022-02-02 00:16 UTC, bordoni approved these changes

2022-02-02 14:41 UTC, merged