[ET-1249] Fixed template path not working for installations with `v2` in dir path.
the-events-calendar/tribe-common pull request #1699
Opened 2022-01-31 03:38 UTC by rafsuntaskin

[ET-1249]
[BTRIA-920]

**Description:**
If the WordPress installation directory had `v2` in the path then templates that are coming from the `v2` directory in our plugins were not working.

2022-01-31 15:52 UTC, bordoni requested changes

2022-01-31 17:09 UTC, rafsuntaskin commented on src/Tribe/Utils/Paths.php
> +		}
If the WP install directory has `v2` in the directory path then this method just trims out the second `v2` from our plugin structure. So, it produces a wrong template path.

See how the `v2` is missing from the result in the plugin path.
https://d.pr/i/wou00R

2022-01-31 17:58 UTC, bordoni commented on src/Tribe/Utils/Paths.php
> +		}
I am not sure why it would be trimming out any V2 from the path. V2 is supposed to be in the path as many times as needed.

2022-02-01 04:46 UTC, bordoni commented on src/Tribe/Utils/Paths.php
> +		}
This particular piece of code does not remove the v2 in any place. Would love to see where in the stack that is happening.

2022-02-14 12:11 UTC, rafsuntaskin commented on src/Tribe/Utils/Paths.php
> +		}
@bordoni it was not removing `v2` exactly. It was removing anything that is found more than once in the directory path: https://github.com/the-events-calendar/tribe-common/blob/c0cc21f3938e2ee4c4d8525ac8de3ef010d614db/src/Tribe/Utils/Paths.php#L65-L71

2022-02-14 15:17 UTC, lucatume commented on src/Tribe/Utils/Paths.php
> +		}
That trimming and removal is in place to allow paths that both have and not have `vx` in place to correctly resolve. Used in RBE code.

2022-02-16 16:29 UTC, bordoni commented
So in debuggin me and @rafsuntaskin found that this `Path::merge()` method has a lot of potential for bugs.
We might need to ditch it for now:
O `Template::get_template_file()` we need to replace `Path::merge()` with the following:
```
			$folder_path = $folder['path'];
			if ( is_string( $folder_path ) ) {
				$folder_path = (array) explode( '/', $folder_path );
			}

			// Build the File Path
			$file = implode( '/', array_merge( $folder_path, $name ) );
```

2022-03-07 18:45 UTC, closed without merging