Avoid loops caused by meta update tracker.
the-events-calendar/tribe-common pull request #1758
Opened 2022-05-20 16:45 UTC by Camwyn

We run `filter_watch_updated_meta` on the `update_post_metadata` hook, and then we run `update_post_meta` inside it.

Let's prevent looping.

2022-05-21 02:59 UTC, bordoni requested changes

2022-05-21 02:59 UTC, bordoni commented on src/Tribe/Tracker.php
> +		remove_filter( 'update_post_metadata', [ $this, 'filter_watch_updated_meta' ], PHP_INT_MAX - 1 );
No need to use `PHP_INT_MAX` give it a normal priority that is not 10, and we are all good.

2022-05-23 08:19 UTC, lucatume submitted a review, later dismissed

2022-07-21 23:33 UTC, bordoni approved these changes

2022-07-22 16:28 UTC, merged