Hotfix: Freemius update
the-events-calendar/tribe-common pull request #1781
Opened 2022-07-20 17:17 UTC by Camwyn

Not sure if we care about the mode changes, the rest looks legit.

[TEC-4430]

2022-07-20 17:30 UTC, Camwyn commented
Both allow and skip appear to work as expected on new installs of TEC or ET.
The **only** issue I have seen is dismissing the notices when both are installed - one of them needs to be dismissed twice.

2022-07-20 18:08 UTC, borkweb commented
It looks like a submodule hash update for tribe-common-styles snuck into this PR

2022-07-20 19:54 UTC, Camwyn commented
> It looks like a submodule hash update for tribe-common-styles snuck into this PR

Fixed - thanks!

2022-07-21 15:37 UTC, EugeneKyale requested changes
Can we remove all these empty files?

2022-07-21 16:11 UTC, borkweb approved these changes

2022-07-21 16:14 UTC, EugeneKyale approved these changes

2022-07-21 16:14 UTC, borkweb commented on vendor/freemius/includes/class-freemius.php
> +                $secure_auth = defined( 'SECURE_AUTH_KEY' ) ? SECURE_AUTH_KEY : '';
This is code from the Freemius SDK, so we should not modify it.

2022-07-21 16:15 UTC, Camwyn commented on vendor/freemius/includes/class-freemius.php
> +                $secure_auth = defined( 'SECURE_AUTH_KEY' ) ? SECURE_AUTH_KEY : '';
This isn't our code - we're not going to edit it

2022-07-21 16:15 UTC, merged