[ET-1734] Make fields mobile friendly
the-events-calendar/tribe-common pull request #1919
Opened 2023-05-12 21:31 UTC by codingmusician

### Ticket
[ET-1734]

### Description
Addressing a few things that came up during a DQA pass for ET. Mostly making the text fields mobile friendly.

2023-05-15 18:25 UTC, bordoni requested changes
Missing artifacts.

2023-05-15 19:59 UTC, redscar approved these changes

2023-05-15 23:17 UTC, bordoni submitted a review, later dismissed

2023-05-16 17:52 UTC, redscar approved these changes

2023-05-16 17:56 UTC, merged