Fix the `Tribe__Data` class
the-events-calendar/tribe-common pull request #2017
Opened 2023-11-21 15:24 UTC by Camwyn

So that it conforms to the classes it implements in PHP 8+

[TEC-4992]

2023-11-22 09:29 UTC, lucatume requested changes
The `next` method should not return any value.

2023-12-22 04:14 UTC, stratease approved these changes
Looks good. For when a release is ready.

2023-12-22 04:14 UTC, stratease commented
This didn't have the CR tag, but it looks ready for review?

2024-01-08 16:11 UTC, EugeneKyale approved these changes

2024-01-10 18:41 UTC, merged