Adding date fns and removing momentjs libs. Some proposed approaches.
the-events-calendar/tribe-common pull request #2076
Opened 2024-04-25 02:33 UTC by stratease

### 🎫 Ticket

[TEC-4242]

### 🗒️ Description

Updating our javascript modules to leverage `date-fns` and vanilla JS instead of `moment`. This update touches Block Editor and Classic Editor differently.

### 🎥 Artifacts 

![image](https://github.com/the-events-calendar/tribe-common/assets/2826045/e95c28ff-93b2-4bcf-9255-5c111f6ebc15)

### ✔️ Checklist
- [ ] Changelog entry in the `readme.txt` file.
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [ ] Are all the **required** tests passing?
- [ ] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [ ] Check the base branch for your PR.
- [ ] Add your PR to the project board for the release.

2024-04-25 02:33 UTC, stratease commented on jest.setup.js
> -moment.tz.setDefault( 'UTC' );
Will we need this? Global settings?

2024-04-25 02:35 UTC, stratease commented on src/modules/elements/time-picker/element.js
> +		return dateUtil
```suggestion
		return dateUtil
```
Maybe we abstract out whatever we use inside our "util". This avoids being tied to a particular lib, centralizing a dependency?

2024-04-25 02:40 UTC, stratease reviewed
Just a thought, but if we migrate directly "inline" it could be quite cumbersome to do. I don't recommend we clone `moments` api, but perhaps we abstract out a bit and hide the implementation details. 

For example: 

Currently it's API is like this:
```
var comparison_end_time = moment( obj.end_time, 'h:mm a' ).format( 'HH:mm' );
```
And if we directly move to `date-fns` it would be something like this:
```
var comparison_start_time = obj.start_time ? dateFns.format( dateFns.toDate( obj.start_date + ' ' + obj.start_time ), 'HH:mm' ) : null;
```
with potentially more refactoring to be done to handle a native `Date` vs `moment`. 

Perhaps we middle ground, and use `date-fns` and `vanilla` inside a util that will hide the implementation details.

I'm not sold on either way, both have pros and cons.

2024-04-26 20:33 UTC, bordoni requested changes
We need to update the `package-safelist.json`

2024-05-14 16:51 UTC, Camwyn commented
We wound up going with Dayjs for now

2024-05-14 16:51 UTC, closed without merging