SLR Support
the-events-calendar/tribe-common pull request #2081
Opened 2024-05-03 13:10 UTC by lucatume

2024-05-09 02:49 UTC, bordoni submitted a review, later dismissed
I wonder which branch we should use, I would urge this to be released with the plugin consolidation. So probably `bucket/plugin-consolidation`

2024-05-10 13:54 UTC, Camwyn approved these changes

2024-05-10 13:54 UTC, Camwyn commented on src/Tribe/Assets.php
> +	 * @since TBD Emptied of all hooks in favor fo the stellarwp/assets library.
```suggestion
	 * @since TBD Emptied of all hooks in favor of the stellarwp/assets library.
```

2024-05-16 16:26 UTC, stratease commented on package.json
> +  "version": "5.4.0-dev",
We skipped 5.3?

2024-05-16 16:31 UTC, stratease requested changes

2024-05-16 16:31 UTC, stratease commented on src/functions/template-tags/general.php
> +	 * @param string $default    Value to return if no such option is found.
Can you fix the rest of the docblock spacing, since you started?

2024-10-30 13:45 UTC, merged