Merge Event Automator in Common
the-events-calendar/tribe-common pull request #2083
Opened 2024-05-09 01:11 UTC by pattihis

### 🎫 Ticket

[EVA-142]

### 🗒️ Description

Merging Event Automator into common.

### ✔️ Checklist
- [ ] Changelog entry in the `readme.txt` file.
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [ ] Are all the **required** tests passing?
- [ ] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [ ] Check the base branch for your PR.
- [ ] Add your PR to the project board for the release.

2024-05-09 02:44 UTC, stratease requested changes
Just namespacing.

2024-05-09 02:44 UTC, stratease commented on src/Common/Event_Automator/Admin/Tabs/Integrations.php
> +namespace TEC\Common\Event_Automator\Admin\Tabs;
```suggestion
namespace TEC\Event_Automator\Admin\Tabs;
```
Keep namespacing the same.

2024-05-14 21:36 UTC, stratease approved these changes

2024-05-15 05:25 UTC, bordoni approved these changes

2024-05-15 16:19 UTC, merged