Resolve sniffer's errors and warning in src/admin-views/
the-events-calendar/tribe-common pull request #2124
Opened 2024-06-24 17:16 UTC by pattihis

### 🗒️ Description

Follow-up [to this PR](https://github.com/the-events-calendar/tribe-common/pull/2121) to resolve code sniffer's errors and warnings.

### ✔️ Checklist
- [ ] Changelog entry in the `readme.txt` file.
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [ ] Are all the **required** tests passing?
- [ ] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [x] Check the base branch for your PR.
- [x] Add your PR to the project board for the release.

2024-06-25 00:38 UTC, stratease approved these changes
Seems ok. Let's get a second approve this is a huge PR, not confident I didn't miss something.

2024-06-25 04:18 UTC, bordoni approved these changes

2024-06-26 15:59 UTC, bordoni requested changes

2024-06-26 15:59 UTC, bordoni commented on src/admin-views/troubleshooting/ea-status/server-connection.php
> +	<td><?php echo wp_kses_post( $notes ); ?></td>
We dont need to do this again. there was a comment about how the escaping is handled above. maybe add the ignore for PHPCS.

2024-06-26 15:59 UTC, bordoni commented on src/admin-views/troubleshooting/ea-status/scheduler-status.php
> +	<td><?php echo wp_kses_post( $notes ); ?></td>
This was handled above. Not need to clean again, add the PHPCS ignore

2024-06-26 15:59 UTC, bordoni commented on src/admin-views/troubleshooting/ea-status/meetup.php
> +	<td><?php echo wp_kses_post( $notes ); ?></td>
This was handled above. Not need to clean again, add the PHPCS ignore

2024-06-26 15:59 UTC, bordoni commented on src/admin-views/troubleshooting/ea-status/license-key.php
> +	<td><?php echo wp_kses_post( $notes ); ?></td>
This was handled above. Not need to clean again, add the PHPCS ignore

2024-06-26 15:59 UTC, bordoni commented on src/admin-views/troubleshooting/ea-status/eventbrite.php
> +	<td><?php echo wp_kses_post( $notes ); ?></td>
This was handled above. Not need to clean again, add the PHPCS ignore

2024-06-26 15:59 UTC, bordoni commented on src/admin-views/troubleshooting/ea-status/current-usage.php
> +	<td><?php echo wp_kses_post( $notes ); ?></td>
This was handled above. Not need to clean again, add the PHPCS ignore

2024-06-26 15:59 UTC, bordoni commented on src/admin-views/troubleshooting/ea-status/current-status.php
> +	<td><?php echo wp_kses_post( $notes ); ?></td>
This was handled above. Not need to clean again, add the PHPCS ignore

2024-06-26 15:59 UTC, bordoni commented on src/admin-views/troubleshooting/common-issues.php
> +						printf( esc_html( $common_issue['solution'] ), wp_kses_post( $label ) );
There is no need to `wp_kses_post` here, its too expensive to keep running this all the time.

2024-06-26 15:59 UTC, bordoni commented on src/admin-views/troubleshooting.php
> +		});
All of these changes are not what we want. Removed a bunch of spaces.

2024-06-28 15:02 UTC, bordoni submitted a review, later dismissed

2024-07-01 23:34 UTC, bordoni approved these changes

2024-07-02 05:19 UTC, merged