Updated logic with concat of plugins for update notice.
the-events-calendar/tribe-common pull request #2134
Opened 2024-07-06 00:39 UTC by stratease

### 🎫 Ticket

[TEC-5118]

### 🗒️ Description

Updated to concat api.

### 🎥 Artifacts 

### ✔️ Checklist
- [ ] Changelog entry in the `readme.txt` file.
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [ ] Are all the **required** tests passing?
- [ ] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [ ] Check the base branch for your PR.
- [ ] Add your PR to the project board for the release.

[TEC-5118]: https://stellarwp.atlassian.net/browse/TEC-5118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-07-06 01:36 UTC, bordoni submitted a review, later dismissed
Address the Code Sniffer.

2024-07-06 04:04 UTC, rafsuntaskin commented on src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
> +	protected static array $plugin_updated_names = [];
```suggestion
	protected static array<string,string> $plugin_updated_names = [];
```

2024-07-06 04:08 UTC, rafsuntaskin requested changes

2024-07-06 04:08 UTC, rafsuntaskin commented on src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
> +	 * @var array
```suggestion
	 * @var array<string, string>
```

2024-07-06 04:08 UTC, rafsuntaskin commented on src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
> +		if( ! in_array( $this->get_plugin_updated_name() , self::$plugin_updated_names ) ) {
Let's use strict for lookup.
```suggestion
		if( ! in_array( $this->get_plugin_updated_name(), self::$plugin_updated_names, true ) ) {
```

2024-07-06 04:08 UTC, rafsuntaskin commented on src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
> +			'<a target="_blank" href="https://evnt.is/1bdy">',
```suggestion
			'<a target="_blank" href="https://evnt.is/1bdy" rel="noopener noreferrer">',
```

2024-07-08 15:02 UTC, Camwyn approved these changes

2024-07-08 15:07 UTC, merged