[SL-157] Support Uplink Licensing
the-events-calendar/tribe-common pull request #2139
Opened 2024-07-10 17:36 UTC by dpanta94

### 🎫 Ticket

[SL-157]

### 🗒️ Description

Provides a way for Uplink registered plugins to be displayed in License Tab.

It will hide legacy fields when it finds the same plugin being registered through Uplink

### 🎥 Artifacts 

### ✔️ Checklist
- [ ] Changelog entry in the `readme.txt` file.
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [x] Are all the **required** tests passing?
- [x] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [ ] Check the base branch for your PR.
- [ ] Add your PR to the project board for the release.

2024-07-16 18:50 UTC, redscar approved these changes

2024-07-16 18:56 UTC, redscar approved these changes
Approved, the wpunit tests are failing due to the older version of uplink. Once we get the version of uplink correct the tests should pass without issue.

The check tests locally use `composer require stellarwp/uplink:dev-feat/fluent-form-builder --prefer-source`

2024-07-23 11:14 UTC, lucatume reviewed
Same question about user cap check I left on the Uplink repository.

2024-07-23 11:14 UTC, lucatume commented on tests/wpunit/Common/Libraries/Uplink/Controller_Test.php
> +		// Retrieve the collection and the specific resource
The current user is `0` (not logged in), should the license fields render at all?

2024-07-29 07:52 UTC, lucatume requested changes

2024-07-29 07:52 UTC, lucatume commented on src/Common/Libraries/Uplink/Controller.php
> +<?php
If all is required by the  Uplink functionality is one file, why not move it to the root?
From `./Uplink/Controller.php` to `./Uplink.php`.

2024-07-30 11:43 UTC, lucatume approved these changes

2024-07-30 12:11 UTC, merged