Help Hub - DQA fixes, Mobile menu fixes
the-events-calendar/tribe-common pull request #2259
Opened 2024-11-08 20:41 UTC by redscar

### 🗒️ Description
This fixes more DQA issues. @codingmusician helped me with the responsive styling of Help Hub.

I added in the mobile menu as well.

### 🎥 Artifacts 

[Help_Hub_Mobile_Styles.webm](https://github.com/user-attachments/assets/e46b60bb-9cfd-42be-ac6b-d1dde56081c1)

2024-11-08 21:16 UTC, rafsuntaskin commented on src/admin-views/help-hub.php
> +	</div>
Please add some more aria attributes for the dialog and closing buttons like ` role="dialog"`

2024-11-08 22:18 UTC, codingmusician requested changes
Some CSS ordering issues I found.

2024-11-08 22:18 UTC, codingmusician commented on src/resources/postcss/help-hub.pcss
> +	padding-bottom: var(--tec-spacer-4);
```suggestion
	padding-bottom: var(--tec-spacer-4);
	width: auto;
```

2024-11-08 22:18 UTC, codingmusician commented on src/resources/postcss/help-hub.pcss
> +	width: calc(100% - var(--tec-spacer-4) * 2);
```suggestion
	border: 1px solid var(--tec-color-border-default);
	margin: 0 auto auto 0;
	width: calc(100% - var(--tec-spacer-4) * 2);
```

2024-11-08 22:18 UTC, codingmusician commented on src/resources/postcss/help-hub.pcss
> +	min-height: auto;
```suggestion
	display: flex;
	max-width: 100%;
	min-height: auto;
	width: 100%;
```

2024-11-08 22:18 UTC, codingmusician commented on src/resources/postcss/help-hub.pcss
> +		margin: 0 var(--tec-spacer-3);
```suggestion
		height: 750px;
		margin: 0 var(--tec-spacer-3);
		width: calc(100% - var(--tec-spacer-3) * 2);
```

2024-11-08 22:18 UTC, codingmusician commented on src/resources/postcss/help-hub.pcss
> +		flex-grow: 1;
```suggestion
		flex-grow: 1;
		max-width: initial;
		width: auto;
```

2024-11-11 14:12 UTC, codingmusician approved these changes

2024-11-11 14:13 UTC, Camwyn approved these changes

2024-11-11 14:13 UTC, Camwyn commented on src/admin-views/help-hub.php
> +	<dialog id="tec-settings-nav-modal" class="tec-settings-form__modal" aria-labelledby="tec-settings-nav-modal-title" aria-modal="true" role="dialog">
`aria-labelledby` or `aria-describedby`? Iffy here, there's not a lot of content. I'll leave that up to you.

2024-11-11 14:25 UTC, merged