Creating tests for Tribe__PUE__Notices class.
the-events-calendar/tribe-common pull request #2332
Opened 2024-12-20 16:19 UTC by redscar

### 🎫 Ticket

[TICKET_ID]

### 🗒️ Description

### 🎥 Artifacts 

### ✔️ Checklist
- [ ] Ran `npm run changelog` to add changelog file(s). More info [here](https://docs.theeventscalendar.com/developer/git/changelogs/#process)
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [ ] Are all the **required** tests passing?
- [ ] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [ ] Check the base branch for your PR.
- [ ] Add your PR to the project board for the release.

2024-12-20 16:22 UTC, dpanta94 requested changes

2024-12-20 16:22 UTC, dpanta94 commented on src/Tribe/PUE/Notices.php
> +		 */
Not potentially this needs to happen ! and actually ive looked the code i dont get why this needs to be a merge at all....

why not $this->notices = $this->saved_notices ?

2025-01-08 18:48 UTC, dpanta94 requested changes

2025-01-08 18:48 UTC, dpanta94 commented on src/Tribe/PUE/Notices.php
> +			update_option( self::STORE_KEY, $saved_notices );
Why save here ?

2025-01-08 18:48 UTC, dpanta94 commented on src/Tribe/PUE/Notices.php
> +		$this->saved_notices = $saved_notices;
You need to clear prior to this or you'll exhaust the memory again

2025-01-08 18:48 UTC, dpanta94 commented on src/Tribe/PUE/Notices.php
> +		$this->notices = $this->sanitize_notices( wp_parse_args( $this->notices, $this->saved_notices ) );
This becomes an issue you have to clear as soon as possible otherwise you risk memory exhaution

2025-01-09 11:39 UTC, dpanta94 requested changes
Some TBDs

2025-01-09 11:39 UTC, dpanta94 commented on src/Tribe/PUE/Notices.php
> +	 * @return void
```suggestion
	 * ensure `save_notices()` is called after invoking this method.
	 *
	 * @since TBD
	 * 
	 * @return void
```

2025-01-09 11:39 UTC, dpanta94 commented on src/Tribe/PUE/Notices.php
> +	 * @return array Sanitized notices.
```suggestion
	 * @param array $notices The array of notices to sanitize.
	 *
	 * @since TBD
	 *
	 * @return array Sanitized notices.
```

2025-01-09 15:54 UTC, Camwyn reviewed
A couple questions...

2025-01-09 15:54 UTC, Camwyn commented on src/Tribe/PUE/Notices.php
> +				$plugin_list = [];
One question: if it's not an array, what is it? Are we "losing data" here?

2025-01-09 15:55 UTC, dpanta94 commented on src/Tribe/PUE/Notices.php
> +				$plugin_list = [];
See the test cases of how we handle that as well, but a quick answer is if its not an array for us it is now invalid and we filter it out :D

2025-01-09 16:24 UTC, Camwyn approved these changes

2025-01-09 16:25 UTC, merged